import { Broker, PrismaClient, type Prisma } from '@prisma/client';

const cookServers = (brokers: Broker[]): Prisma.HostServerCreateInput[] => {
  const brokerMap: Record<
    string,
    Prisma.BrokerCreateNestedOneWithoutHostServerInput
  > = brokers.reduce((acc, cur) => {
    acc[cur.key] = {
      connect: {
        id: cur.id,
      },
    };
    return acc;
  }, {});

  const zhisui_company: Prisma.CompanyCreateNestedOneWithoutHostServerInput = {
    connectOrCreate: {
      where: {
        key: 'zhisui',
      },
      create: {
        key: 'zhisui',
        name: '致邃投资',
      },
    },
  };

  const zouwu_company: Prisma.CompanyCreateNestedOneWithoutHostServerInput = {
    connectOrCreate: {
      where: {
        key: 'zouwu',
      },
      create: {
        key: 'zouwu',
        name: '驺吾',
      },
    },
  };

  return [
    {
      name: '国君(上海)-12762',
      ssh_host: 'localhost',
      ssh_user: 'root',
      ssh_port: 12762,
      host_ip: '10.113.155.72',
      broker: brokerMap['guojun'],
      market: 'SH',
      home_dir: '/root',
      company: zhisui_company,
    },
    {
      name: '国君(上海)-12722',
      ssh_host: 'localhost',
      ssh_user: 'root',
      ssh_port: 12722,
      host_ip: '10.113.155.71',
      broker: brokerMap['guojun'],
      market: 'SH',
      home_dir: '/root',
      company: zhisui_company,
      is_master: true,
    },
    {
      name: '国君(深圳)-12766',
      ssh_host: 'localhost',
      ssh_user: 'root',
      ssh_port: 12766,
      host_ip: '10.197.91.58',
      broker: brokerMap['guojun'],
      market: 'SZ',
      home_dir: '/root',
      company: zhisui_company,
    },
    {
      name: '国君(深圳)-12724',
      ssh_host: 'localhost',
      ssh_user: 'root',
      ssh_port: 12724,
      host_ip: '10.197.91.55',
      home_dir: '/root',
      broker: brokerMap['guojun'],
      market: 'SZ',
      company: zhisui_company,
    },
    {
      name: '国君(深圳)-12726',
      ssh_host: 'localhost',
      ssh_user: 'root',
      ssh_port: 12726,
      host_ip: '10.197.91.56',
      broker: brokerMap['guojun'],
      market: 'SZ',
      home_dir: '/root',
      company: zhisui_company,
      is_master: true,
    },
    {
      name: '国君(深圳)-12764',
      ssh_host: 'localhost',
      ssh_user: 'root',
      ssh_port: 12764,
      host_ip: '10.197.91.57',
      broker: brokerMap['guojun'],
      market: 'SZ',
      home_dir: '/root',
      company: zhisui_company,
    },
    {
      name: '中泰(上海)-12710',
      ssh_host: 'localhost',
      ssh_user: 'admin',
      ssh_port: 12710,
      host_ip: '10.101.5.177',
      broker: brokerMap['xtp'],
      market: 'SH',
      home_dir: '/home/admin',
      company: zhisui_company,
      is_master: true,
    },
    {
      name: '中泰(上海)-12730',
      ssh_host: 'localhost',
      ssh_user: 'admin',
      ssh_port: 12730,
      host_ip: '10.101.5.178',
      broker: brokerMap['xtp'],
      market: 'SH',
      home_dir: '/home/admin',
      company: zhisui_company,
    },
    {
      name: '中泰(上海)-驺吾-12714',
      ssh_host: 'localhost',
      ssh_user: 'admin',
      ssh_port: 12714,
      host_ip: '10.101.2.42',
      broker: brokerMap['xtp'],
      market: 'SH',
      home_dir: '/home/admin',
      company: zouwu_company,
    },
    {
      name: '中泰(深圳)-12706',
      ssh_host: 'localhost',
      ssh_user: 'admin',
      ssh_port: 12706,
      host_ip: '10.36.117.118',
      broker: brokerMap['xtp'],
      market: 'SZ',
      home_dir: '/home/admin',
      company: zhisui_company,
      is_master: true,
    },
    {
      name: '中泰(深圳)-12712',
      ssh_host: 'localhost',
      ssh_user: 'admin',
      ssh_port: 12712,
      host_ip: '10.36.117.109',
      broker: brokerMap['xtp'],
      market: 'SZ',
      home_dir: '/home/admin',
      company: zhisui_company,
    },
    {
      name: '中泰(深圳)-12752',
      ssh_host: 'localhost',
      ssh_user: 'admin',
      ssh_port: 12752,
      host_ip: '10.36.121.136',
      broker: brokerMap['xtp'],
      market: 'SZ',
      home_dir: '/home/admin',
      company: zhisui_company,
    },
    {
      name: '中泰(深圳)-12760',
      ssh_host: 'localhost',
      ssh_user: 'admin',
      ssh_port: 12760,
      host_ip: '10.36.120.156',
      broker: brokerMap['xtp'],
      market: 'SZ',
      home_dir: '/home/admin',
      company: zhisui_company,
    },
    {
      name: '中泰(深圳)-12703',
      ssh_host: 'localhost',
      ssh_user: 'admin',
      ssh_port: 12703,
      host_ip: '10.101.2.89',
      broker: brokerMap['xtp'],
      market: 'SZ',
      home_dir: '/home/admin',
      company: zhisui_company,
    },
    {
      name: '中泰(深圳)-驺吾-13702',
      ssh_host: 'localhost',
      ssh_user: 'admin',
      ssh_port: 13702,
      host_ip: '10.36.121.42',
      broker: brokerMap['xtp'],
      market: 'SZ',
      home_dir: '/home/admin',
      company: zouwu_company,
    },
    {
      name: '中金-深圳-12772',
      ssh_host: 'localhost',
      ssh_user: 'root',
      ssh_port: 12772,
      host_ip: '10.128.144.55',
      broker: brokerMap['zhongjin'],
      market: 'SZ',
      home_dir: '/root',
      company: zhisui_company,
      is_master: true,
    },
    {
      name: '中金-深圳-12774',
      ssh_host: 'localhost',
      ssh_user: 'root',
      ssh_port: 12774,
      host_ip: '10.128.144.56',
      broker: brokerMap['zhongjin'],
      market: 'SZ',
      home_dir: '/root',
      company: zhisui_company,
    },
    {
      name: '中金-深圳-12776',
      ssh_host: 'localhost',
      ssh_user: 'root',
      ssh_port: 12776,
      host_ip: '10.128.144.62',
      broker: brokerMap['zhongjin'],
      market: 'SZ',
      home_dir: '/root',
      active: false,
      company: zhisui_company,
    },
    {
      name: '中金-深圳-12778',
      ssh_host: 'localhost',
      ssh_user: 'root',
      ssh_port: 12778,
      host_ip: '10.128.144.63',
      broker: brokerMap['zhongjin'],
      market: 'SZ',
      home_dir: '/root',
      active: false,
      company: zhisui_company,
    },
    {
      name: '中金-上海-12780',
      ssh_host: 'localhost',
      ssh_user: 'root',
      ssh_port: 12780,
      host_ip: '10.129.145.34',
      broker: brokerMap['zhongjin'],
      market: 'SH',
      home_dir: '/root',
      company: zhisui_company,
      is_master: true,
    },
    {
      name: '中金-上海-12782',
      ssh_host: 'localhost',
      ssh_user: 'root',
      ssh_port: 12782,
      host_ip: '10.129.145.35',
      broker: brokerMap['zhongjin'],
      market: 'SH',
      home_dir: '/root',
      active: false,
      company: zhisui_company,
    },
    {
      name: '国信-深圳-12732',
      ssh_host: 'localhost',
      ssh_user: 'root',
      ssh_port: 12732,
      host_ip: '10.35.81.164',
      home_dir: '/root',
      broker: brokerMap['guoxin'],
      market: 'SZ',
      company: zhisui_company,
      is_master: true,
    },
    {
      name: '国信-深圳-12734',
      ssh_host: 'localhost',
      ssh_user: 'root',
      ssh_port: 12734,
      host_ip: '10.35.81.166',
      home_dir: '/root',
      broker: brokerMap['guoxin'],
      market: 'SZ',
      company: zhisui_company,
    },
    {
      name: '国信-深圳-12740',
      ssh_host: 'localhost',
      ssh_user: 'root',
      ssh_port: 12740,
      host_ip: '10.35.81.95',
      home_dir: '/root',
      broker: brokerMap['guoxin'],
      market: 'SZ',
      company: zhisui_company,
    },
    {
      name: '国信-深圳-12742',
      ssh_host: 'localhost',
      ssh_user: 'root',
      ssh_port: 12742,
      host_ip: '10.35.81.205',
      home_dir: '/root',
      broker: brokerMap['guoxin'],
      market: 'SZ',
      company: zhisui_company,
    },
    {
      name: '国信-上海-12736',
      ssh_host: 'localhost',
      ssh_user: 'root',
      ssh_port: 12736,
      host_ip: '10.49.128.132',
      home_dir: '/root',
      broker: brokerMap['guoxin'],
      market: 'SH',
      company: zhisui_company,
      is_master: true,
    },
    {
      name: '国信-上海-12744',
      ssh_host: 'localhost',
      ssh_user: 'root',
      ssh_port: 12744,
      host_ip: '10.49.129.64',
      home_dir: '/root',
      broker: brokerMap['guoxin'],
      market: 'SH',
      company: zhisui_company,
    },
    {
      name: '中金EQ-深圳-50',
      ssh_host: '59.36.190.215',
      ssh_user: 'root',
      ssh_port: 8843,
      host_ip: '59.36.190.215',
      home_dir: '/root',
      broker: brokerMap['zhongjin_eq'],
      market: 'SZ',
      active: false,
      company: zhisui_company,
    },
    {
      name: '中金EQ-深圳-51',
      ssh_host: '59.36.190.216',
      ssh_user: 'root',
      ssh_port: 8843,
      host_ip: '59.36.190.216',
      home_dir: '/root',
      broker: brokerMap['zhongjin_eq'],
      market: 'SZ',
      active: false,
      company: zhisui_company,
    },
    {
      name: '中金EQ-上海-12802',
      ssh_host: 'localhost',
      ssh_user: 'root',
      ssh_port: 12802,
      host_ip: '10.95.221.26',
      home_dir: '/root',
      broker: brokerMap['zhongjin_eq'],
      market: 'SH',
      active: false,
      company: zhisui_company,
    },
    {
      name: '中金EQ-上海-12804',
      ssh_host: 'localhost',
      ssh_user: 'root',
      ssh_port: 12804,
      host_ip: '10.95.221.27',
      home_dir: '/root',
      broker: brokerMap['zhongjin_eq'],
      market: 'SH',
      active: false,
      company: zhisui_company,
    },
    {
      name: '方正-深圳-12812',
      ssh_host: 'localhost',
      ssh_user: 'zszb',
      ssh_port: 12812,
      host_ip: '10.128.7.113',
      home_dir: '/home/zszb',
      broker: brokerMap['fangzheng'],
      market: 'SZ',
      is_master: true,
      company: zhisui_company,
    },
    {
      name: '方正-深圳-12814',
      ssh_host: 'localhost',
      ssh_user: 'zszb',
      ssh_port: 12814,
      host_ip: '10.128.7.114',
      home_dir: '/home/zszb',
      broker: brokerMap['fangzheng'],
      market: 'SZ',
      is_master: true,
      company: zhisui_company,
    },
    {
      name: '方正-上海-12816',
      ssh_host: 'localhost',
      ssh_user: 'zszb',
      ssh_port: 12816,
      host_ip: '10.129.6.49',
      home_dir: '/home/zszb',
      broker: brokerMap['fangzheng'],
      market: 'SH',
      company: zhisui_company,
    },
    {
      name: '招商-上海-12822',
      ssh_host: 'localhost',
      ssh_user: 'root',
      ssh_port: 12822,
      host_ip: '10.236.27.181',
      home_dir: '/root',
      broker: brokerMap['zhaoshang_dma'],
      market: 'SH',
      active: false,
      company: zhisui_company,
    },
    {
      name: '招商-深圳-12824',
      ssh_host: 'localhost',
      ssh_user: 'root',
      ssh_port: 12824,
      host_ip: '10.237.30.208',
      home_dir: '/root',
      broker: brokerMap['zhaoshang_dma'],
      market: 'SH',
      active: false,
      company: zhisui_company,
    },
    {
      name: '招商-深圳-12826',
      ssh_host: 'localhost',
      ssh_user: 'root',
      ssh_port: 12826,
      host_ip: '10.237.30.209',
      home_dir: '/root',
      broker: brokerMap['zhaoshang_dma'],
      market: 'SH',
      active: false,
      company: zhisui_company,
    },
    {
      name: '安信-上海-12842',
      ssh_host: 'localhost',
      ssh_user: 'zwtz',
      ssh_port: 12842,
      host_ip: '10.10.91.84',
      home_dir: '/home/zwtz',
      broker: brokerMap['anxin'],
      market: 'SH',
      active: false,
      company: zhisui_company,
    },
    {
      name: '安信-深圳-12844',
      ssh_host: 'localhost',
      ssh_user: 'zwtz',
      ssh_port: 12844,
      host_ip: '10.10.91.160',
      home_dir: '/home/zwtz',
      broker: brokerMap['anxin'],
      market: 'SZ',
      active: false,
      company: zhisui_company,
    },
    {
      name: '安信-深圳-12846',
      ssh_host: 'localhost',
      ssh_user: 'zwtz',
      ssh_port: 12846,
      host_ip: '10.10.91.161',
      home_dir: '/home/zwtz',
      broker: brokerMap['anxin'],
      market: 'SZ',
      active: false,
      company: zhisui_company,
    },
    {
      name: '中信-上海-12852',
      ssh_host: 'localhost',
      ssh_user: 'zhisui',
      ssh_port: 12852,
      host_ip: '10.12.182.248',
      home_dir: '/home/zhisui',
      broker: brokerMap['zhongxin'],
      market: 'SH',
      company: zhisui_company,
      is_master: true,
    },
    {
      name: '中信-深圳-12854',
      ssh_host: 'localhost',
      ssh_user: 'zhisui',
      ssh_port: 12854,
      host_ip: '10.27.91.226',
      home_dir: '/home/zhisui',
      broker: brokerMap['zhongxin'],
      market: 'SZ',
      company: zhisui_company,
      is_master: true,
    },
    {
      name: '中信-深圳-12856',
      ssh_host: 'localhost',
      ssh_user: 'zhisui',
      ssh_port: 12856,
      host_ip: '10.27.91.225',
      home_dir: '/home/zhisui',
      broker: brokerMap['zhongxin'],
      market: 'SZ',
      company: zhisui_company,
    },
  ];
};

export async function seedHostServer(prisma: PrismaClient) {
  const brokers = await prisma.broker.findMany();

  const servers = cookServers(brokers);

  for (const server of servers) {
    await prisma.hostServer.create({
      data: server,
    });
  }

  console.log('HostServer seed done.');
}
